apiVersion: apps/v1
kind: Deployment
metadata:
  name: topsquad
  namespace: topsquad
  labels:
    app.kubernetes.io/name: topsquad
    app.kubernetes.io/instance: topsquad
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: topsquad
      app.kubernetes.io/instance: topsquad
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topsquad
        app.kubernetes.io/instance: topsquad
    spec:
      containers:
        - name: topsquad
          image: hadensmith/topsquad:4b612aaaab16a07e9892f5796098d47d2ecd9e72
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: topsquad-env
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: topsquad-env
                  key: CLERK_SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: topsquad-env
                  key: DATABASE_URL
            - name: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: topsquad-env
                  key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
            - name: NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
              valueFrom:
                secretKeyRef:
                  name: topsquad-env
                  key: NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET

