apiVersion: v1
kind: Service
metadata:
  name: topsquad-svc
  namespace: topsquad
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: topsquad
    app.kubernetes.io/instance: topsquad
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP

